//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Town { get; set; }
        public int Index { get; set; }
        public string Street { get; set; }
        public int House { get; set; }
        public Nullable<int> Flat { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
