//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UniversityEntities : DbContext
    {
        public UniversityEntities()
            : base("name=UniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Student> Student { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> sp_InsertAddress(Nullable<int> studentID, string town, Nullable<int> index, string street, Nullable<int> house, Nullable<int> flat)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(int));
    
            var townParameter = town != null ?
                new ObjectParameter("Town", town) :
                new ObjectParameter("Town", typeof(string));
    
            var indexParameter = index.HasValue ?
                new ObjectParameter("Index", index) :
                new ObjectParameter("Index", typeof(int));
    
            var streetParameter = street != null ?
                new ObjectParameter("Street", street) :
                new ObjectParameter("Street", typeof(string));
    
            var houseParameter = house.HasValue ?
                new ObjectParameter("House", house) :
                new ObjectParameter("House", typeof(int));
    
            var flatParameter = flat.HasValue ?
                new ObjectParameter("Flat", flat) :
                new ObjectParameter("Flat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_InsertAddress", studentIDParameter, townParameter, indexParameter, streetParameter, houseParameter, flatParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_InsertStudent(string nAME, string sPECIALITY, Nullable<int> aGE, Nullable<System.DateTime> bIRTHDAY, Nullable<int> cOURSE, string sEX, Nullable<double> aVGSCORE)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var sPECIALITYParameter = sPECIALITY != null ?
                new ObjectParameter("SPECIALITY", sPECIALITY) :
                new ObjectParameter("SPECIALITY", typeof(string));
    
            var aGEParameter = aGE.HasValue ?
                new ObjectParameter("AGE", aGE) :
                new ObjectParameter("AGE", typeof(int));
    
            var bIRTHDAYParameter = bIRTHDAY.HasValue ?
                new ObjectParameter("BIRTHDAY", bIRTHDAY) :
                new ObjectParameter("BIRTHDAY", typeof(System.DateTime));
    
            var cOURSEParameter = cOURSE.HasValue ?
                new ObjectParameter("COURSE", cOURSE) :
                new ObjectParameter("COURSE", typeof(int));
    
            var sEXParameter = sEX != null ?
                new ObjectParameter("SEX", sEX) :
                new ObjectParameter("SEX", typeof(string));
    
            var aVGSCOREParameter = aVGSCORE.HasValue ?
                new ObjectParameter("AVGSCORE", aVGSCORE) :
                new ObjectParameter("AVGSCORE", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_InsertStudent", nAMEParameter, sPECIALITYParameter, aGEParameter, bIRTHDAYParameter, cOURSEParameter, sEXParameter, aVGSCOREParameter);
        }
    }
}
